// The plugin's settings wiring: observers per key, pane registration, teardown, and bulk case-key
// regeneration (cases only, forced, notifications skipped, auto-exports re-run for that library).
var asked = [], saved = [], errors = [], observers = [], unregistered = [], registeredPanes = [], scheduled = [];
function eq(a, b, m) { if (JSON.stringify(a) !== JSON.stringify(b)) errors.push(m + ': got ' + JSON.stringify(a) + ' want ' + JSON.stringify(b)); }
var prefs = {};
var Zotero = { logError: function (e) { errors.push('logError: ' + e.message); },
	Prefs: { get: function (k) { return prefs[k]; },
		registerObserver: function (name, fn) { var s = { name: name }; observers.push({ s: s, fn: fn }); return s; },
		unregisterObserver: function (s) { unregistered.push(s.name); } },
	PreferencePanes: { register: function (o) { registeredPanes.push(o); return Promise.resolve('pane-id'); } },
	Search: function () { this.addCondition = function () {}; this.search = function () { return Promise.resolve([1, 2, 3, 4]); }; },
	CreatorTypes: { getPrimaryIDForType: function () { return 1; } } };
var HC = new Function('Zotero', read('addon/hicite-export.js') + '; return HiCite;')(Zotero);
HC.id = 'hicite-export@zotero.local'; HC.rootURI = 'jar:file:///x.xpi!/';
HC.schedule = function (libs) { scheduled.push(libs === null ? null : Array.from(libs)); };

HC.registerSettings().then(function () {
	eq(observers.map(function (o) { return o.s.name; }).sort(), ['translators.hicite.caseKeys', 'translators.hicite.includeUrls', 'translators.hicite.keySource', 'translators.hicite.keyStore', 'translators.hicite.maxAuthors', 'translators.hicite.omitRedundantSite',
		'translators.hicite.refresh', 'translators.hicite.shortTitleInline'], 'one observer per setting, plus the refresh signal');
	observers[0].fn(); eq(scheduled, [null], 'a changed setting re-runs every auto-export');
	eq(registeredPanes.length, 1, 'one Settings pane');
	eq([registeredPanes[0].pluginID, registeredPanes[0].src, registeredPanes[0].scripts, registeredPanes[0].label],
		['hicite-export@zotero.local', 'jar:file:///x.xpi!/preferences.xhtml', ['jar:file:///x.xpi!/preferences.js'], 'hicite'], 'pane registration arguments');
	// every setting has a default the plugin, prefs.js and the translator header agree on
	var dflt = read('addon/prefs.js'), hdr = read('addon/translator/hicite.js');
	Object.keys(HC.SETTINGS).forEach(function (k) {
		var v = HC.SETTINGS[k], lit = typeof v === 'string' ? '"' + v + '"' : String(v);
		if (dflt.indexOf('extensions.zotero.translators.hicite.' + k + '", ' + lit + ')') < 0) errors.push('prefs.js default differs for ' + k);
		if (hdr.indexOf('"hicite.' + k + '": ' + lit) < 0) errors.push('translator header default differs for ' + k);
	});
	Zotero.HiCitePrefs = {}; HC.destroy();
	eq(unregistered.length, 8, 'destroy unregisters every observer'); eq(typeof Zotero.HiCitePrefs, 'undefined', 'destroy removes the pane script global');
	// regenerateCaseKeys
	saved = [];
	function mk(id, type, extra) { return { id: id, itemType: type, _extra: extra || '', pinCalled: false }; }
	var its = { 1: mk(1, 'case', 'Citation Key: old1'), 2: mk(2, 'book'), 3: mk(3, 'case', 'Citation Key: same'), 4: mk(4, 'case') };
	HC.scopeItems = function () { return Promise.resolve([its[1], its[2], its[3], its[4]]); };
	HC.getKey = function (i) { return (/Citation Key: (\S+)/.exec(i._extra) || [])[1] || ''; };
	HC.pin = function (i, o) { saved.push([i.id, o && o.force]); return Promise.resolve(i.id === 3 ? 'same' : 'new' + i.id); };
	scheduled.length = 0;
	return HC.regenerateCaseKeys({ libraryID: 7, collectionKey: null });
}).then(function (r) {
	eq(r, { total: 3, changed: 2, cancelled: false }, 'counts: 3 cases, 2 keys changed (the book is skipped)');
	eq(scheduled, [[7]], 'auto-exports for that library re-run');
	eq(saved, [[1, true], [3, true], [4, true]], 'only cases, and each key is regenerated by force (not merely kept)');
	// Regenerate All: every regular item, only after the user confirms
	saved = []; scheduled.length = 0;
	return HC.regenerateKeys({ libraryID: 7, collectionKey: null }, { confirm: function (n) { asked.push(n); return Promise.resolve(false); } });
}).then(function (r) {
	eq(r.cancelled, true, 'cancelling the confirmation cancels'); eq(saved, [], 'nothing is regenerated when the user says no'); eq(scheduled, [], 'and no export is scheduled'); eq(asked, [4], 'the confirmation is told how many items are affected');
	return HC.regenerateKeys({ libraryID: 7, collectionKey: null }, { confirm: function () { return true; } });
}).then(function (r) {
	eq(r, { total: 4, changed: 3, cancelled: false }, 'confirmed: all four items (case and book), keys changed on three');
	eq(saved, [[1, true], [2, true], [3, true], [4, true]], 'every item is regenerated by force');
	eq(scheduled, [[7]], 'auto-exports re-run once'); eq(HC.confirmRegenerate('items', 4, '"X"'), false, 'no way to ask (no prompt service): do nothing');
}).catch(function (e) { errors.push('exception ' + e.message + '\n' + e.stack); }).then(function () {
	print(errors.length ? 'FAIL\n' + errors.join('\n') : 'settings OK (observers, pane registration, defaults agree, teardown, case regeneration)');
});
